# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-MediaWikiDump
version:      0.22
version_from: lib/Parse/MediaWikiDump.pm
installdirs:  site
requires:
    Test::More:                    0
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
