--- #YAML:1.0
name:               Parse-MediaWikiDump
version:            1.01
abstract:           Tools to process MediaWiki dump files
author:
    - Tyler Riddle <triddle@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Devel::Cycle:         1.11
    List::Util:           0
    PadWalker:            0
    Scalar::Util:         0
    Test::Exception:      0
    Test::Memory::Cycle:  0
    Test::More:           0
    XML::Parser:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
